export const labels = {
  USERNAME: "Username",
  FIRST_NAME: "First Name",
  LAST_NAME: "Last Name",
  EMAIL: "Email",
  PASSWORD: "Password",
  REPEAT_PASSWORD: "Repeat Password",
  DONT_HAVE_ACCOUNT: "Don't have an account?",
  ALREADY_HAVE_ACCOUNT: "Already have an account?",
  USER_UPDATED: "User updated",
  FILTER_KEYWORD_SEARCH: "Keyword Search",
  ADD_NEW_USER: "New User",
  SELECT_ROLE: "Select role",
  POST_DESCRIPTION: "Description",
  SELECT_MIN_RANK: "Select Min Rank",
  SELECT_MAX_RANK: "Select Max Rank",
  RANK_RANGE: "Rank Range",
  COMMENT: "Comment",
  COMMENT_PLACEHOLDER: "Share your thoughts...",
  POST_ABORT: "Reset",
  POST_SUBMIT: "Submit Post",
  COMMENT_SUBMIT: "Submit Comment",
  SHOW_COMMENTS: "Show comments",
  HIDE_COMMENTS: "Hide comments",
  CONFIRM_REMOVE_POST_HEADER: "Delete post",
  CONFIRM_REMOVE_POST_TEXT: "Are you sure you want delete the entire post?",
  CONFIRM_REMOVE_COMMENT_HEADER: "Delete comment",
  CONFIRM_REMOVE_COMMENT_TEXT: "Are you sure you want delete this comment?",
  LOOKING_FOR: "Looking For",
  UPGRADE_TO_PREMIUM: "Upgrade to Premium",
  PREMIUM_PLAN: "Premium Plan",
  CONFIRM_HEADER_POST_LIMIT_HEADER: "Daily Post Limit",
  CONFIRM_HEADER_POST_LIMIT_MESSAGE:
    "You’ve hit your daily post limit. It will reset in 24 hours. Want unlimited posts? Go Premium!",
  CONFIRM_HEADER_COMMENT_LIMIT_HEADER: "Daily Comment Limit",
  CONFIRM_HEADER_COMMENT_LIMIT_MESSAGE:
    "You’ve hit your daily comment limit. It will reset in 24 hours. Want unlimited comments? Go Premium!",
  BAN_FORM: "Ban Form",
  BAN_REASON: "Ban Reason",
};

export const buttons = {
  HOME: "Home",
  SAVE: "Save",
  CANCEL: "Cancel",
  ADD_USER: "Add User",
  SIGN_IN: "Sign In",
  LOGOUT: "Logout",
  POST_HISTORY: "Post History",
  ADMIN_DASHBOARD: "Admin Dashboard",
  USER_MANAGEMENT: "User management",
  CREATE_POST: "Create a Post",
  POSTS: "Posts",
  SUBMIT_POST: "Post Now",
  EDIT_POST: "Edit post",
  SUBMIT_CHANGES: "Submit changes",
  DELETE_POST: "Delete",
  EDIT_COMMENT: "Edit comment",
  DELETE_COMMENT: "Delete",
  GO_PREMIUM: "Upgrade to Premium",
  SUBMIT_BAN: "Submit Ban",
};

export const errorMessage = {
  FIRST_NAME_REQUIRED: "First name is required",
  LAST_NAME_REQUIRED: "Last name is required",
  USERNAME_REQUIRED: "Username is required",
  ROLE_REQUIRED: "Role is required",
  USERNAME_PASSWORD_REQUIRED: "Username and password is required",
  COUNTRY_REQUIRED: "Country is required",
  VALID_EMAIL: "Enter a valid email address 'example@mail.com'",
  PASSWORD_VALIDATION:
    "Password must be at least 8 characters, include 1 uppercase letter, 1 number, and 1 special symbol.",
  PASSWORD_NOT_MATCH: "Passwords do not match",
  PASSWORD_AT_LEAST_8_CHARS: "At least 8 characters required.",
  PASSWORD_AT_LEAST_1_UPPERCASE: "At least 1 uppercase letter required.",
  PASSWORD_AT_LEAST_1_NUMBER: "At least 1 number required.",
  PASSWORD_AT_LEAST_1_SPECIAL_CHAR: "At least 1 special symbol required.",
  USERNAME_EXISTS: "Username already exists.",
  EMAIL_EXISTS: "Email already exists.",
  DESCRIPTION: "Description is required.",
  RANK_SELECTION: "Min and Max Rank are required.",
  POSITIONS_SELECTION: "At least one position is required.",
  BAN_REASON_REQUIRED: "Ban reason is required.",
};
